---
ID: "95020a2b-b17c-43b8-af66-cebb58abb60e"
Parent: "55c8cedd-722e-4a38-abe2-ae613c67e79c"
Template: "55c8cedd-722e-4a38-abe2-ae613c67e79c"
Path: /sitecore/templates/Foundation/Videos/Video Provider Setting/__Standard Values
DB: master
SharedFields:
- ID: "4a491450-7092-4060-9c0f-dd5c60e92ad1"
  Hint: Provider ID
  Value: $name
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211124T204830Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rcabral
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rcabral
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2000333c-0e7d-41d9-9f3c-2546c81b24a3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rcabral
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211124T204835Z
