---
ID: "8d472fcc-31d9-4cb3-873c-b0305ed56635"
Parent: "f82bbf8b-3eae-4698-8cc4-9591f9b90050"
Template: "f82bbf8b-3eae-4698-8cc4-9591f9b90050"
Path: /sitecore/templates/Feature/Timeline/Timeline Labels/__Standard Values
DB: master
Languages:
- Language: en
  Fields:
  - ID: "67806312-1f24-48b3-87b3-ec9eb9f005a2"
    Hint: Show More
    Value: Show More
  - ID: "e581543e-e30a-4fbd-b437-0b51b3cc403f"
    Hint: Show Less
    Value: Show Less
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211230T160304Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bfe5d680-d5c5-4a9f-9637-e0fa90beef36"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rcabral
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211230T160310Z
