---
ID: "c918e350-732d-48c7-ac80-cd93f1277eee"
Parent: "15586de1-ca42-4b3e-8219-d7fb72b9654d"
Template: "15586de1-ca42-4b3e-8219-d7fb72b9654d"
Path: /sitecore/templates/Feature/Navigation/Footer/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220304T160100Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5337c368-e787-4865-b2c9-d5788b7628c4"
      Hint: Copyright
      Value: Copyright © 2022 Send Pizza
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6851102d-c254-4f1d-84e9-ebdc0e791a4a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220304T160117Z
