---
ID: "9bab9355-988c-40d1-b71e-9c1dcdbd7cf2"
Parent: "4061f32e-4062-4274-8f08-2797989d5d3d"
Template: "4061f32e-4062-4274-8f08-2797989d5d3d"
Path: /sitecore/templates/Feature/Primary Content/Accordion Container/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1d77f0d1-b8eb-4125-9709-5cd0e1e143d8"
      Hint: Heading
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211222T195632Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rcabral
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rcabral
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "30d872bc-1271-4568-aca2-d10cc07468cc"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rcabral
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211222T195728Z
    - ID: "de64927a-dccb-4d04-a882-a305c0c4d0b6"
      Hint: Intro Text
      Value: <p>Quisque erat nulla, pellentesque eget volutpat nec, laoreet a neque. Donec eget tellus erat. Aenean ac vulputate justo, vel mollis diam. Aliquam non urna diam.</p>
