---
ID: "3f4df48b-1506-4877-9abf-457adfe19980"
Parent: "60913af9-a3e9-4642-8b01-ac18579b7924"
Template: "60913af9-a3e9-4642-8b01-ac18579b7924"
Path: /sitecore/templates/Feature/Primary Content/Content Section Media/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211124T203128Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rcabral
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rcabral
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c2308c5e-d81a-477b-aa77-efbd38ac8092"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rcabral
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211223T181537Z
    - ID: "eca9851b-4230-4c95-84d0-e9fd00e833be"
      Hint: Section Image
      Value: |
        <image mediaid="{84EAF4D7-59B1-4C89-B98A-D8DDAD87F10B}" />
